In [ ]:
#1. What is a Python library? Why do we use Python libraries?

In [ ]:
A Python library is a collection of modules and functions that extend the capabilities of the Python programming language.
These libraries provide pre-written, reusable code that can be easily integrated into your own Python programs, saving time and effort in development. 
Libraries often contain implementations of common algorithms, data structures, and functionalities, allowing developers to leverage existing code rather 
than writing everything from scratch.

Python libraries serve various purposes, including:

Code Reusability: Libraries provide a set of pre-built functions and modules that you can use in your projects, saving you from reinventing the wheel 
and allowing you to build on the work of others.

Efficiency: Libraries are usually optimized for performance and correctness. By using established and well-tested libraries, you can benefit from the
expertise of experienced developers and ensure that your code is reliable and efficient.

Rapid Development: Libraries speed up the development process by providing high-level abstractions and ready-to-use components. This allows developers
to focus on solving specific problems rather than dealing with low-level details.

Community Support: Python has a large and active community of developers who contribute to and maintain numerous libraries. This community support means
that you can often find solutions to common problems or get help when you encounter difficulties.

Specialized Functionality: Python libraries cover a wide range of domains, from data science (e.g., NumPy, pandas, scikit-learn) to web development 
(e.g., Flask, Django) and machine learning (e.g., TensorFlow, PyTorch). Using these specialized libraries allows you to leverage the expertise of domain-specific developers and tools.

In summary, Python libraries enhance the functionality of the language, promote code reuse, and enable developers to build robust and efficient
solutions by leveraging existing code and expertise.

In [ ]:
#2. What is the difference between Numpy array and List?

In [ ]:
NumPy arrays and Python lists are both used to store and manipulate collections of data, but there are several key differences
between them:

1.Type of Elements:

List: A Python list can contain elements of different data types. You can have integers, strings, floats, or even other lists as elements within a single list.
NumPy Array: NumPy arrays are homogeneous, meaning all elements must be of the same data type. This homogeneity allows for more efficient storage and operations.

2.Performance:

List: Lists are generally slower than NumPy arrays for numerical operations. Python lists are dynamic and can resize, which adds some overhead.
NumPy Array: NumPy arrays are statically typed and more memory efficient. They are implemented in C and provide better performance for numerical computations.

3.Memory Usage:

List: Lists are more memory-intensive as they store additional information such as the type of each element.
NumPy Array: NumPy arrays are more memory-efficient due to their fixed type and compact storage.

4.Convenience and Functionality:

List: Lists provide a more general-purpose collection with various built-in methods. They are flexible but might not be as efficient for numerical operations.
NumPy Array: NumPy arrays come with a rich set of functions and methods specifically designed for numerical operations. This includes vectorized operations,
which can significantly improve performance.

5.Syntax:

List: Lists are part of the core Python language and have a straightforward syntax for creation, e.g., my_list = [1, 2, 3].
NumPy Array: NumPy arrays are created using the numpy.array() constructor, and their syntax allows for more advanced operations on arrays.

6.Size and Shape:

List: Lists can be multi-dimensional, but they are not designed for numerical computations.
NumPy Array: NumPy arrays are explicitly designed for numerical operations and can be multi-dimensional. They are widely used in scientific computing
and data analysis.

In summary, while lists are more general-purpose and flexible, NumPy arrays are optimized for numerical operations, providing better performance and 
memory efficiency for tasks involving numerical data. Choosing between them depends on the specific requirements of your application.

In [ ]:
#3.Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [2]:
import numpy as np

# Define the array
my_array = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

# Get shape
shape = my_array.shape

# Get size
size = my_array.size

# Get dimensions
dimensions = my_array.ndim

print("Shape:", shape)
print("Size:", size)
print("Dimensions:", dimensions)



Shape: (3, 4)
Size: 12
Dimensions: 2


In [ ]:
#44. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [1]:
import numpy as np

# Define the array
my_array = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

# Access the first row
first_row = my_array[0, :]

print("First Row:", first_row)


First Row: [1 2 3 4]


In [ ]:
#5 How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [3]:
import numpy as np

# Define the array
my_array = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

# Access the element at the third row (index 2) and fourth column (index 3)
element = my_array[2, 3]

print("Element at the third row and fourth column:", element)


Element at the third row and fourth column: 12


In [ ]:
#6 . Write co^e to extract all o^^-in^exe^ elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [4]:
import numpy as np

# Define the array
my_array = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

# Extract all odd-indexed elements
odd_elements = my_array[::2, ::2]

print("Odd-indexed elements:")
print(odd_elements)


Odd-indexed elements:
[[ 1  3]
 [ 9 11]]


In [ ]:
#7 How can you generate a random 3x3 matrix with values between 0 and 1?

In [5]:
import numpy as np

# Generate a random 3x3 matrix with values between 0 and 1
random_matrix = np.random.rand(3, 3)

print("Random 3x3 matrix:")
print(random_matrix)


Random 3x3 matrix:
[[0.57928085 0.38059921 0.39736913]
 [0.4773205  0.56587276 0.732447  ]
 [0.83478747 0.3338585  0.11889783]]


In [ ]:
#8 8. Describe the difference between np.random.rand and np.random.randn?

In [ ]:
1.np.random.rand:

Generates random values from a uniform distribution between 0 (inclusive) and 1 (exclusive).
The syntax is np.random.rand(d0, d1, ..., dn), where d0, d1, ..., dn are the dimensions of the output array.
Example:
import numpy as np
random_values = np.random.rand(3, 3)

2.np.random.randn:

Generates random values from a standard normal distribution (mean = 0, standard deviation = 1).
The syntax is np.random.randn(d0, d1, ..., dn), where d0, d1, ..., dn are the dimensions of the output array.
Example:
import numpy as np
random_values = np.random.randn(3, 3)

In summary:

.np.random.rand generates values from a uniform distribution between 0 and 1.
.np.random.randn generates values from a standard normal distribution with mean 0 and standard deviation 1.
Both functions can be used to generate random numbers, but the distribution they sample from is different. Choose the one that best fits the 
requirements of your specific use case.






In [ ]:
#9 9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [86]:
import numpy as np

# Define the array
my_array = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

# Increase the dimension by adding a new axis
new_dimension_array = my_array[:, :, np.newaxis]

# Alternatively, you can use np.expand_dims
# new_dimension_array = np.expand_dims(my_array, axis=2)

print("Original Array:")
print(my_array)

print("\nArray with Increased Dimension:")
print(new_dimension_array)


Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array with Increased Dimension:
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


In [ ]:
#10 How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [87]:
import numpy as np

# Define the array
my_array = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

# Transpose the array using .T
transposed_array_t = my_array.T

# Alternatively, transpose using numpy.transpose()
# transposed_array = np.transpose(my_array)

print("Original Array:")
print(my_array)

print("\nTransposed Array:")
print(transposed_array_t)


Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed Array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [ ]:
#11 Consider the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Perform the following operation using Python1
1. Index wise multiplication
2. Matix multiplication
3. Add both the matrics
4. Subtact matix B from A 
5. Divide Matix B by A

In [91]:
import numpy as np

# Define matrices A and B
matrix_A = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

matrix_B = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

# 1. Index wise multiplication
index_wise_multiplication = matrix_A * matrix_B

# 2. Matrix multiplication
matrix_multiplication = np.dot(matrix_A, matrix_B.T)  # Assuming you want to multiply A by the transpose of B

# Add both matrices
added_matrices = matrix_A + matrix_B

# 3. Subtract matrix B from A
subtracted_matrix = matrix_A - matrix_B

# 4. Divide matrix B by A
# Note: Division by zero may occur, so be cautious about this operation
divided_matrix = np.divide(matrix_B, matrix_A)

# Display results
print("\n1. Index Wise Multiplication:")
print(index_wise_multiplication)

print("\n2. Matrix Multiplication:")
print(matrix_multiplication)

print("\nAdded Matrices:")
print(added_matrices)

print("\n3. Subtracted Matrix:")
print(subtracted_matrix)

print("\n4. Divided Matrix:")
print(divided_matrix)



1. Index Wise Multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

2. Matrix Multiplication:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

Added Matrices:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

3. Subtracted Matrix:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

4. Divided Matrix:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#12 Which function in Numpy can be used to swap the byte order of an array?

In [92]:
# In NumPy, the byteswap function can be used to swap the byte order of an array. This function swaps the byte order of the elements
in the array without changing the actual data. It's particularly useful when dealing with binary data and handling data across different
systems with different byte orders (e.g., little-endian and big-endian).
#Example
import numpy as np

# Create an example array
original_array = np.array([1, 256], dtype=np.int16)

# Swap the byte order using byteswap
swapped_array = original_array.byteswap()

print("Original Array:")
print(original_array)

print("\nSwapped Array:")
print(swapped_array)


Original Array:
[  1 256]

Swapped Array:
[256   1]


In [ ]:
#13 What is the significance of the np.linalg.inv function?

In [ ]:
Here are some key points regarding the significance of np.linalg.inv:

1.Solving Linear Systems: One common application is in solving systems of linear equations. If you have a system of equations 
represented by the matrix equation Ax = B, where A is a coefficient matrix, x is the column vector of variables, and B is 
the column vector of constants, you can find the solution vector x by multiplying both sides of the equation by the inverse of A: 

2.Eigenvalue Problems: The inverse of a matrix is often used in eigenvalue problems and in the diagonalization of matrices.

3.Numerical Stability: While the concept of the inverse is straightforward in theory, in practice, numerical issues can arise.
The np.linalg.inv function is implemented to handle these issues and provide a stable and accurate computation of the matrix inverse.

In [94]:
#The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix. The significance of this function lies
#in its applications in linear algebra and solving systems of linear equations.

#Given a square matrix A, if there exists a matrix A^(-1) such that the product of A and A^(-1) is the identity matrix (I),
#then A^(-1) is the inverse of A. 

import numpy as np

# Define a square matrix
matrix_A = np.array([[4, 7],
                     [2, 6]])

# Compute the inverse
inverse_A = np.linalg.inv(matrix_A)

print("Original Matrix:")
print(matrix_A)

print("\nInverse Matrix:")
print(inverse_A)






Original Matrix:
[[4 7]
 [2 6]]

Inverse Matrix:
[[ 0.6 -0.7]
 [-0.2  0.4]]


In [ ]:
#14What does the np.reshape function do, and how is it used?

In [ ]:
The np.reshape function in NumPy is used to change the shape of an array without changing its data.
It allows you to modify the dimensions (number of rows and columns) of the array while keeping the total number of elements constant. 
The reshaped array shares the same data with the original array;
only the view of the data changes.

In [95]:
#reshaping 1 D to 2 D array
import numpy as np

original_array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = np.reshape(original_array, (2, 3))

print("Original Array:")
print(original_array)

print("\nReshaped Array:")
print(reshaped_array)


Original Array:
[1 2 3 4 5 6]

Reshaped Array:
[[1 2 3]
 [4 5 6]]


In [96]:
#reshaping 2D to 1D
import numpy as np

original_array = np.array([[1, 2, 3],
                           [4, 5, 6]])
reshaped_array = np.reshape(original_array, 6)

print("Original Array:")
print(original_array)

print("\nReshaped Array:")
print(reshaped_array)


Original Array:
[[1 2 3]
 [4 5 6]]

Reshaped Array:
[1 2 3 4 5 6]


In [ ]:
#14What is broadcasting in Numpy?

In [ ]:
Broadcasting in NumPy is a powerful mechanism that allows arrays of different shapes to be combined and operated upon together.
In cases where the shapes of the arrays being operated upon are not the same, NumPy automatically broadcasts the smaller array
to match the shape of the larger array. This avoids the need for explicit replication of the smaller array, making operations more concise and efficient.

The broadcasting rules allow NumPy to perform element-wise operations on arrays of different shapes, extending or "broadcasting"
the smaller array to match the shape of the larger array. The dimensions of the arrays are compared element-wise, starting from
the rightmost dimension, and the following rules are applied:

1.If the dimensions are equal, or if one of the dimensions is 1, they are compatible.
2.If dimensions are not equal and none of them is 1, the arrays are incompatible, and broadcasting will raise an error.

In [97]:
import numpy as np

# Larger array (3x3)
larger_array = np.array([[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]])

# Smaller array (1x3)
smaller_array = np.array([10, 20, 30])

# Broadcasting the smaller array to the shape of the larger array
result = larger_array + smaller_array

print("Larger Array:")
print(larger_array)

print("\nSmaller Array:")
print(smaller_array)

print("\nResult after Broadcasting:")
print(result)


Larger Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Smaller Array:
[10 20 30]

Result after Broadcasting:
[[11 22 33]
 [14 25 36]
 [17 28 39]]
